spring:

  datasource:
    url: jdbc:mysql://localhost:3307/prico
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update

  # Fix error happens when starting application after adding swagger plugin
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

springfox:
  documentation:
    swagger-ui.enabled: true