spring:

  datasource:
    url: jdbc:mysql://localhost:3307/prico
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${auth0.domain}/

  # Fix error happens when starting application after adding swagger plugin
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

springfox:
  documentation:
    swagger-ui.enabled: true

auth0:
  audience: https://prico.com
  domain: dev-ywc7xshec6w6nkoy.us.auth0.com
