name: Build and Test Java Spring Boot Application 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
   
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Tests
      run: mvn test

    - name: Upload Test Report
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
          name: test-results                    # Name of the folder
          path: target/surefire-reports         # Path to test results
