name: Build and Test Java Spring Boot Application 

on:
  push:
    branches: [ "master", "develop"  ]
  pull_request:
    branches: [ "master", "develop" ]
    types: [ opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
   
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Get PR number
      id: pr_number
      run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

    - name: Run tests with coverage
      run: mvn -B clean verify

    - name: Generate JaCoCo coverage report
      run: mvn -B jacoco:report

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: target/site/jacoco/index.html

    - name: Add coverage to PR
      run: |
        # Generate coverage report and parse results
        total_coverage=$(grep -E 'Overall coverage rate:' target/site/jacoco/index.html | awk '{print $4}')
        # Post comment in pull request
        gh pr comment $PR_NUMBER "Total test coverage: $total_coverage%"
